//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MedicSystem.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MEDICIDSEEKDLG              105
#define IDD_MEDICNAMESEEKDLG            106
#define IDD_MEDICTYPESEEKDLG            107
#define IDR_MAINFRAME                   128
#define IDR_MedicSystemTYPE             129
#define IDC_REPORT                      129
#define ID_TAB1_GROUP1                  130
#define ID_GROUP_USER                   130
#define ID_TAB1_BUTTON1                 131
#define ID_USER_ADD                     131
#define ID_TAB1_BUTTON2                 132
#define ID_USER_DEL                     132
#define ID_TAB1_BUTTON3                 133
#define ID_USER_MOD                     133
#define ID_USER_SEEK                    133
#define ID_TAB1                         134
#define ID_TAB_START                    134
#define ID_SEEK_FILTER                  135
#define IDR_SYSTEM                      136
#define IDB_BITMAP1                     137
#define ID_GROUP_SYSTEM                 137
#define ID_USER_CHANGE                  138
#define IDB_BITMAP3                     139
#define IDR_LOGO                        139
#define ID_USER_MODPWD                  139
#define ID_USER_LOGOUT                  140
#define ID_RIBBON_MINIMIZE              141
#define IDR_JPEG1                       142
#define ID_RIBBON_EXPAND                142
#define ID_TAB_SEEK                     143
#define ID_GROUP_SEEK                   144
#define ID_GROUP_OTHERS                 145
#define ID_SEEK_NUMBER                  146
#define IDR_PNG2                        147
#define ID_SEEK_NAME                    147
#define ID_SEEK_TYPE                    148
#define IDR_PNG1                        149
#define ID_SEEK_ALL                     149
#define ID_SEEK_ZERO                    150
#define ID_SEEK_OUTDATE                 151
#define ID_TAB_MANAGER                  152
#define IDR_PNG3                        153
#define ID_GROUP_MEDIC                  153
#define IDR_PNG4                        154
#define ID_TAB_THEME                    154
#define IDD_USER_LOGIN                  155
#define ID_GROUP_STYLE                  155
#define ID_MEDIC_ADD                    156
#define ID_MEDIC_SALE                   157
#define ID_MEDIC_CLEAN                  158
#define ID_STYLE_POPBTN                 159
#define IDR_PNG_THEME                   159
#define ID_GROUP_REPOTR                 159
#define ID_GROUP_FONT                   160
#define ID_STYLE_FONT1                  161
#define IDB_USERS_LIST                  162
#define ID_STYLE_FONT2                  162
#define IDI_USERS                       163
#define ID_STYLE_FONT3                  163
#define IDR_PNG_MINI                    164
#define ID_STYLE_FONT4                  164
#define IDR_PNG_DEFAULT                 166
#define IDB_USER_RIBBON                 167
#define IDR_PNG_MODPWD                  168
#define IDR_PNG_EXIT                    169
#define IDR_PNG_CHANGE                  170
#define IDD_USER_ADD                    171
#define IDD_USER_DEL                    173
#define IDD_USER_SEEK                   174
#define IDR_PNG_SEEK                    177
#define IDR_PNG_FONT                    182
#define IDR_MENU1                       183
#define ID_STYLE_FONT                   184
#define IDD_REPORT_SEEK                 185
#define IDR_PNG_FIND                    187
#define IDR_PNG_MEDIC                   188
#define IDR_PNG6                        189
#define IDR_PNG_CLEAN                   189
#define IDD_USER_MODPW                  190
#define IDI_ICON1                       191
#define IDI_ICON_PWD                    191
#define IDD_USER_CHANGE                 191
#define IDR_MENU_POPU                   192
#define ID_MENU_POPU                    192
#define IDD_MEDIC_SEEK_ID               193
#define IDD_MEDIC_SEEK_NAME             194
#define IDD_MEDIC_SEEK_TYPE             195
#define IDD_MEDIC_STORE                 197
#define IDD_MEDIC_CLEAN                 198
#define IDD_DIALOG1                     199
#define IDD_MEDIC_SALE                  199
#define IDR_PNG5                        202
#define IDR_PNG_SYSICON                 202
#define IDD_DIALOG2                     204
#define IDD_FIELDCHOOSER                204
#define ID_STYLE_SKIN                   205
#define ID_REPORT_SET                   206
#define ID_GROUP_SKIN                   207
#define IDB_PNG1                        212
#define IDB_BITMAP2                     215
#define IDB_WAITING_ZDLG                215
#define IDC_EDIT_ACCOUNT                1001
#define IDC_EDIT_PASSWD                 1002
#define IDC_COMBO_TYPE                  1004
#define IDC_REGISTER_ACCOUNT            1007
#define IDC_REGISTER_PWD1               1008
#define IDC_REGISTER_PWD2               1009
#define IDC_REGISTER_COMBO              1011
#define IDC_REGISTER_LIST               1012
#define IDC_COMBO1                      1013
#define IDC_EDIT1                       1014
#define IDC_LIST1                       1015
#define IDC_EDIT_NAME                   1015
#define IDC_SEEK_RADIO1                 1016
#define IDC_EDIT2                       1016
#define IDC_SEEK_RADIO2                 1017
#define IDC_EDIT3                       1017
#define IDC_EDIT_NUMBER                 1017
#define IDC_SEEK_LIST                   1018
#define IDC_EDIT_PRICE                  1018
#define IDC_SEEK_COMBO                  1019
#define IDC_EDIT4                       1019
#define IDC_EDIT_KEEP                   1019
#define IDC_SEEK_EDIT                   1020
#define IDC_EDIT_COMPANY                1020
#define IDC_EDIT_FILTER                 1022
#define IDC_DATETIMEPICKER1             1024
#define IDC_EDIT_DATE                   1024
#define IDC_EDIT_ID                     1031
#define IDC_EDIT_TYPE                   1032
#define IDC_RADIO_ZERO                  1033
#define IDC_RADIO_OUTDATE               1034
#define IDC_LIST2                       1034
#define IDC_BUTTON1                     1035
#define IDUNDO                          1035
#define IDC_SALE_ADD                    1036
#define IDC_SALE_DEL                    1037
#define IDC_MEDIC_NUMBER                1039
#define IDC_MEDIC_NAME                  1040
#define IDC_MEDIC_TYPE                  1041
#define ID_BUTTON32772                  32772
#define ID_OPEN                         32774
#define ID_STYLES_OFFICE2007BLUE        32775
#define ID_STYLES_OFFICE2007SILVER      32776
#define ID_STYLES_OFFICE2007BLACK       32777
#define ID_STYLES_WINDOWS7SCENIC        32778
#define ID_STYLES_BLUE2010              32782
#define ID_STYLES_OFFICE2010            32783
#define ID_STYLES_OFFICE2010BLUE        32784
#define ID_STYLES_OFFICE2010SILVER      32785
#define ID_STYLES_OFFICE2010BLACK       32786
#define ID_POPU_ADD                     32809
#define ID_POPU_DEL                     32810
#define ID_POPU_SEEK                    32811
#define ID_POPU_MOD                     32812
#define ID_MENU_CHANGE                  32813
#define ID_POPU_CHANGE                  32814
#define ID_FIELD_CHOOSER                32815
#define ID_32815                        32815
#define ID_32816                        32816
#define ID_32817                        32817
#define ID_SKIN1                        32818
#define ID_SKIN2                        32819
#define ID_SKIN3                        32820
#define ID_32821                        32821
#define ID_32822                        32822
#define ID_SKIN4                        32823
#define ID_SKIN5                        32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
